#+SETUPFILE: setup.org
#+TITLE: Blog Posts Revolving Around Coding, Configuring Emacs, and Neuroscience

* Introduction
- I am a Neuroscientist and Research Associate Professor at the University of Utah - Department of Psychiatry.
- My research focuses on how aging, neurodegenerative diseases, and neuropsychiatric disorders affect cognitive and motor function using neuropsychological testing and motor behavioral assessments.
- With functional and structural Magnetic Resonance Imaging I try to understand and predict such behavioral outcomes.
- Most of my published work is freely available through [[https://pubmed.ncbi.nlm.nih.gov/?term=Koppelmans+V+%5Bauth%5D&sort=date][PubMed]].
- To process and analyze my research data, I mainly use R and Python with Emacs as my IDE.
- Here, I plan to post about anything that helped me automate or streamline my work.

* Posts
- 2026-03-08 [[file:2026/20260308_EmacsElpyPytonDocker.org][Setting up Python Inside a Docker Container for Emacs Elpy]]
- 2026-03-09 [[file:2026/20260309_GifScreenCast.org][gif-screencast on Ubuntu 24.04]]
