name: Export
on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Emacs
        run: sudo apt install emacs-nox --yes
      - name: Build the site
        run: emacs --batch --no-init-file --eval "(require 'ox-publish)" --eval "(setq org-publish-project-alist '((\"blog\" :base-directory \".\" :base-extension \"org\" :publishing-directory \"./public\" :publishing-function org-html-publish-to-html :recursive t)))" --eval "(org-publish-all t)"
      - name: Copy static files
        run: |
          mkdir -p public
          rsync -av \
          --exclude='.git' \
          --exclude='*.org' \
          --exclude='public' \
          --exclude='.github' \
          --exclude='*.yml' \
          . public/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
